<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class SkillSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $skills = [
            // Languages
            ['PHP', 'Languages'],
            ['JavaScript', 'Languages'],
            ['TypeScript', 'Languages'],
            ['Python', 'Languages'],
            ['Java', 'Languages'],
            ['C#', 'Languages'],
            ['C++', 'Languages'],
            ['C', 'Languages'],
            ['Go', 'Languages'],
            ['Rust', 'Languages'],
            ['Ruby', 'Languages'],
            ['Swift', 'Languages'],
            ['Kotlin', 'Languages'],
            ['Dart', 'Languages'],
            ['Scala', 'Languages'],
            ['Elixir', 'Languages'],
            ['Clojure', 'Languages'],
            ['Haskell', 'Languages'],
            ['Lua', 'Languages'],
            ['R', 'Languages'],
            ['Perl', 'Languages'],
            ['Objective-C', 'Languages'],
            ['Shell/Bash', 'Languages'],
            ['SQL', 'Languages'],
            ['Solidity', 'Languages'],
            ['Zig', 'Languages'],
            ['COBOL', 'Languages'],
            ['Fortran', 'Languages'],
            ['Assembly', 'Languages'],
            ['V', 'Languages'],
            ['Nim', 'Languages'],
            ['Julia', 'Languages'],
            ['OCaml', 'Languages'],
            ['Erlang', 'Languages'],
            ['F#', 'Languages'],
            ['Groovy', 'Languages'],
            ['ABAP', 'Languages'],
            ['Apex', 'Languages'],
            ['MATLAB', 'Languages'],

            // Frontend Frameworks
            ['React', 'Frontend'],
            ['Vue.js', 'Frontend'],
            ['Angular', 'Frontend'],
            ['Svelte', 'Frontend'],
            ['Next.js', 'Frontend'],
            ['Nuxt.js', 'Frontend'],
            ['Astro', 'Frontend'],
            ['Remix', 'Frontend'],
            ['SolidJS', 'Frontend'],
            ['Qwik', 'Frontend'],
            ['Ember.js', 'Frontend'],
            ['Alpine.js', 'Frontend'],
            ['Lit', 'Frontend'],
            ['Preact', 'Frontend'],
            ['Gatsby', 'Frontend'],
            ['Hugo', 'Frontend'],
            ['Eleventy', 'Frontend'],
            ['jQuery', 'Frontend'],
            ['Htmx', 'Frontend'],
            ['Livewire', 'Frontend'],
            ['Inertia.js', 'Frontend'],
            ['Stimulus', 'Frontend'],
            ['Turbo', 'Frontend'],
            ['Hotwire', 'Frontend'],

            // CSS / UI
            ['Tailwind CSS', 'CSS/UI'],
            ['Bootstrap', 'CSS/UI'],
            ['Sass/SCSS', 'CSS/UI'],
            ['CSS Modules', 'CSS/UI'],
            ['Styled Components', 'CSS/UI'],
            ['Material UI', 'CSS/UI'],
            ['Chakra UI', 'CSS/UI'],
            ['Ant Design', 'CSS/UI'],
            ['Shadcn/ui', 'CSS/UI'],
            ['Radix UI', 'CSS/UI'],
            ['Headless UI', 'CSS/UI'],
            ['Vuetify', 'CSS/UI'],
            ['PrimeVue', 'CSS/UI'],
            ['Element Plus', 'CSS/UI'],
            ['Bulma', 'CSS/UI'],
            ['Foundation', 'CSS/UI'],
            ['PostCSS', 'CSS/UI'],
            ['UnoCSS', 'CSS/UI'],
            ['Panda CSS', 'CSS/UI'],
            ['Storybook', 'CSS/UI'],

            // Backend Frameworks
            ['Laravel', 'Backend'],
            ['Symfony', 'Backend'],
            ['Django', 'Backend'],
            ['Flask', 'Backend'],
            ['FastAPI', 'Backend'],
            ['Spring Boot', 'Backend'],
            ['Express.js', 'Backend'],
            ['NestJS', 'Backend'],
            ['Ruby on Rails', 'Backend'],
            ['ASP.NET', 'Backend'],
            ['ASP.NET Core', 'Backend'],
            ['Phoenix', 'Backend'],
            ['Gin', 'Backend'],
            ['Fiber', 'Backend'],
            ['Echo', 'Backend'],
            ['Fastify', 'Backend'],
            ['Koa', 'Backend'],
            ['Hono', 'Backend'],
            ['AdonisJS', 'Backend'],
            ['Actix', 'Backend'],
            ['Axum', 'Backend'],
            ['Rocket', 'Backend'],
            ['Ktor', 'Backend'],
            ['Quarkus', 'Backend'],
            ['Micronaut', 'Backend'],
            ['Strapi', 'Backend'],
            ['Directus', 'Backend'],
            ['Supabase', 'Backend'],
            ['Firebase', 'Backend'],
            ['CodeIgniter', 'Backend'],
            ['CakePHP', 'Backend'],
            ['Lumen', 'Backend'],
            ['Slim', 'Backend'],
            ['Yii', 'Backend'],
            ['Play Framework', 'Backend'],
            ['Vapor', 'Backend'],

            // Mobile
            ['React Native', 'Mobile'],
            ['Flutter', 'Mobile'],
            ['SwiftUI', 'Mobile'],
            ['Jetpack Compose', 'Mobile'],
            ['Expo', 'Mobile'],
            ['Ionic', 'Mobile'],
            ['Capacitor', 'Mobile'],
            ['Xamarin', 'Mobile'],
            ['.NET MAUI', 'Mobile'],
            ['NativeScript', 'Mobile'],
            ['Kotlin Multiplatform', 'Mobile'],
            ['Tauri', 'Mobile'],
            ['Electron', 'Mobile'],

            // Databases
            ['PostgreSQL', 'Databases'],
            ['MySQL', 'Databases'],
            ['MariaDB', 'Databases'],
            ['SQLite', 'Databases'],
            ['SQL Server', 'Databases'],
            ['Oracle DB', 'Databases'],
            ['MongoDB', 'Databases'],
            ['Redis', 'Databases'],
            ['Elasticsearch', 'Databases'],
            ['DynamoDB', 'Databases'],
            ['Cassandra', 'Databases'],
            ['Neo4j', 'Databases'],
            ['CouchDB', 'Databases'],
            ['ClickHouse', 'Databases'],
            ['InfluxDB', 'Databases'],
            ['TimescaleDB', 'Databases'],
            ['Supabase Database', 'Databases'],
            ['PlanetScale', 'Databases'],
            ['Neon', 'Databases'],
            ['CockroachDB', 'Databases'],
            ['ScyllaDB', 'Databases'],
            ['Firebase Realtime DB', 'Databases'],
            ['Firestore', 'Databases'],
            ['Memcached', 'Databases'],
            ['Valkey', 'Databases'],
            ['Dragonfly', 'Databases'],
            ['SurrealDB', 'Databases'],
            ['FaunaDB', 'Databases'],
            ['RavenDB', 'Databases'],

            // DevOps / Cloud
            ['Docker', 'DevOps'],
            ['Kubernetes', 'DevOps'],
            ['AWS', 'Cloud'],
            ['Azure', 'Cloud'],
            ['Google Cloud (GCP)', 'Cloud'],
            ['Terraform', 'DevOps'],
            ['Ansible', 'DevOps'],
            ['Pulumi', 'DevOps'],
            ['GitHub Actions', 'DevOps'],
            ['GitLab CI', 'DevOps'],
            ['Jenkins', 'DevOps'],
            ['CircleCI', 'DevOps'],
            ['ArgoCD', 'DevOps'],
            ['Helm', 'DevOps'],
            ['Nginx', 'DevOps'],
            ['Apache', 'DevOps'],
            ['Caddy', 'DevOps'],
            ['Traefik', 'DevOps'],
            ['Cloudflare', 'DevOps'],
            ['Vercel', 'Cloud'],
            ['Netlify', 'Cloud'],
            ['Heroku', 'Cloud'],
            ['DigitalOcean', 'Cloud'],
            ['Hetzner', 'Cloud'],
            ['Linode', 'Cloud'],
            ['Fly.io', 'Cloud'],
            ['Railway', 'Cloud'],
            ['Render', 'Cloud'],
            ['AWS Lambda', 'Cloud'],
            ['AWS EC2', 'Cloud'],
            ['AWS S3', 'Cloud'],
            ['AWS RDS', 'Cloud'],
            ['AWS ECS', 'Cloud'],
            ['AWS EKS', 'Cloud'],
            ['AWS CloudFront', 'Cloud'],
            ['AWS SQS', 'Cloud'],
            ['AWS SNS', 'Cloud'],
            ['Azure DevOps', 'Cloud'],
            ['Azure Functions', 'Cloud'],
            ['Google Cloud Run', 'Cloud'],
            ['Google Cloud Functions', 'Cloud'],
            ['Vagrant', 'DevOps'],
            ['Packer', 'DevOps'],
            ['Prometheus', 'DevOps'],
            ['Grafana', 'DevOps'],
            ['Datadog', 'DevOps'],
            ['New Relic', 'DevOps'],
            ['Sentry', 'DevOps'],
            ['ELK Stack', 'DevOps'],
            ['Loki', 'DevOps'],
            ['Jaeger', 'DevOps'],
            ['OpenTelemetry', 'DevOps'],

            // Message Queues / Event
            ['RabbitMQ', 'Messaging'],
            ['Apache Kafka', 'Messaging'],
            ['Amazon SQS', 'Messaging'],
            ['NATS', 'Messaging'],
            ['BullMQ', 'Messaging'],
            ['Celery', 'Messaging'],
            ['Laravel Horizon', 'Messaging'],
            ['Sidekiq', 'Messaging'],

            // Testing
            ['Jest', 'Testing'],
            ['Vitest', 'Testing'],
            ['Cypress', 'Testing'],
            ['Playwright', 'Testing'],
            ['Selenium', 'Testing'],
            ['PHPUnit', 'Testing'],
            ['Pest', 'Testing'],
            ['PyTest', 'Testing'],
            ['JUnit', 'Testing'],
            ['Mocha', 'Testing'],
            ['Testing Library', 'Testing'],
            ['Puppeteer', 'Testing'],
            ['k6', 'Testing'],
            ['Locust', 'Testing'],
            ['Artillery', 'Testing'],
            ['RSpec', 'Testing'],
            ['xUnit', 'Testing'],
            ['NUnit', 'Testing'],
            ['Detox', 'Testing'],

            // Build / Tooling
            ['Vite', 'Tooling'],
            ['Webpack', 'Tooling'],
            ['esbuild', 'Tooling'],
            ['Turbopack', 'Tooling'],
            ['Rollup', 'Tooling'],
            ['SWC', 'Tooling'],
            ['Babel', 'Tooling'],
            ['ESLint', 'Tooling'],
            ['Prettier', 'Tooling'],
            ['Biome', 'Tooling'],
            ['pnpm', 'Tooling'],
            ['Yarn', 'Tooling'],
            ['npm', 'Tooling'],
            ['Bun', 'Tooling'],
            ['Deno', 'Tooling'],
            ['Composer', 'Tooling'],
            ['pip', 'Tooling'],
            ['Maven', 'Tooling'],
            ['Gradle', 'Tooling'],
            ['Cargo', 'Tooling'],
            ['Turborepo', 'Tooling'],
            ['Nx', 'Tooling'],
            ['Lerna', 'Tooling'],
            ['Monorepo', 'Tooling'],

            // Data / ML / AI
            ['TensorFlow', 'AI/ML'],
            ['PyTorch', 'AI/ML'],
            ['scikit-learn', 'AI/ML'],
            ['Pandas', 'AI/ML'],
            ['NumPy', 'AI/ML'],
            ['OpenAI API', 'AI/ML'],
            ['LangChain', 'AI/ML'],
            ['Hugging Face', 'AI/ML'],
            ['Apache Spark', 'AI/ML'],
            ['Apache Airflow', 'AI/ML'],
            ['dbt', 'AI/ML'],
            ['Snowflake', 'AI/ML'],
            ['BigQuery', 'AI/ML'],
            ['Redshift', 'AI/ML'],
            ['Databricks', 'AI/ML'],
            ['MLflow', 'AI/ML'],
            ['Keras', 'AI/ML'],
            ['OpenCV', 'AI/ML'],
            ['NLTK', 'AI/ML'],
            ['spaCy', 'AI/ML'],
            ['RAG', 'AI/ML'],
            ['Vector Databases', 'AI/ML'],
            ['Pinecone', 'AI/ML'],
            ['Weaviate', 'AI/ML'],
            ['Anthropic API', 'AI/ML'],
            ['Ollama', 'AI/ML'],

            // CMS / E-commerce
            ['WordPress', 'CMS'],
            ['Drupal', 'CMS'],
            ['Magento', 'CMS'],
            ['Shopify', 'CMS'],
            ['WooCommerce', 'CMS'],
            ['Contentful', 'CMS'],
            ['Sanity', 'CMS'],
            ['Ghost', 'CMS'],
            ['Payload CMS', 'CMS'],
            ['PrestaShop', 'CMS'],
            ['Medusa.js', 'CMS'],
            ['Saleor', 'CMS'],

            // APIs / Protocols
            ['REST API', 'APIs'],
            ['GraphQL', 'APIs'],
            ['gRPC', 'APIs'],
            ['WebSockets', 'APIs'],
            ['tRPC', 'APIs'],
            ['OpenAPI/Swagger', 'APIs'],
            ['Postman', 'APIs'],
            ['Insomnia', 'APIs'],
            ['Apollo GraphQL', 'APIs'],
            ['Prisma', 'APIs'],
            ['Drizzle ORM', 'APIs'],
            ['TypeORM', 'APIs'],
            ['Sequelize', 'APIs'],
            ['Eloquent', 'APIs'],
            ['Hibernate', 'APIs'],
            ['SQLAlchemy', 'APIs'],
            ['Mongoose', 'APIs'],
            ['Knex.js', 'APIs'],
            ['MikroORM', 'APIs'],

            // Auth / Security
            ['OAuth 2.0', 'Security'],
            ['JWT', 'Security'],
            ['SAML', 'Security'],
            ['Keycloak', 'Security'],
            ['Auth0', 'Security'],
            ['Clerk', 'Security'],
            ['NextAuth.js', 'Security'],
            ['Passport.js', 'Security'],
            ['Laravel Sanctum', 'Security'],
            ['OWASP', 'Security'],
            ['Vault', 'Security'],

            // Version Control
            ['Git', 'Version Control'],
            ['GitHub', 'Version Control'],
            ['GitLab', 'Version Control'],
            ['Bitbucket', 'Version Control'],

            // Design / UX
            ['Figma', 'Design'],
            ['Adobe XD', 'Design'],
            ['Sketch', 'Design'],
            ['Photoshop', 'Design'],
            ['Illustrator', 'Design'],
            ['InVision', 'Design'],
            ['Framer', 'Design'],
            ['Canva', 'Design'],
            ['Zeplin', 'Design'],
            ['Design Systems', 'Design'],
            ['UI/UX Design', 'Design'],
            ['Accessibility (a11y)', 'Design'],
            ['Responsive Design', 'Design'],

            // Project / Agile
            ['Scrum', 'Methodology'],
            ['Kanban', 'Methodology'],
            ['Agile', 'Methodology'],
            ['Jira', 'Methodology'],
            ['Linear', 'Methodology'],
            ['Notion', 'Methodology'],
            ['Trello', 'Methodology'],
            ['Confluence', 'Methodology'],

            // Architecture
            ['Microservices', 'Architecture'],
            ['Serverless', 'Architecture'],
            ['Monolith', 'Architecture'],
            ['Event-Driven Architecture', 'Architecture'],
            ['Domain-Driven Design', 'Architecture'],
            ['CQRS', 'Architecture'],
            ['Event Sourcing', 'Architecture'],
            ['Clean Architecture', 'Architecture'],
            ['Hexagonal Architecture', 'Architecture'],
            ['SOA', 'Architecture'],
            ['TDD', 'Architecture'],
            ['BDD', 'Architecture'],
            ['CI/CD', 'Architecture'],

            // Blockchain / Web3
            ['Ethereum', 'Web3'],
            ['Solana', 'Web3'],
            ['Web3.js', 'Web3'],
            ['Ethers.js', 'Web3'],
            ['Hardhat', 'Web3'],
            ['Truffle', 'Web3'],
            ['Smart Contracts', 'Web3'],

            // Game Dev
            ['Unity', 'Game Dev'],
            ['Unreal Engine', 'Game Dev'],
            ['Godot', 'Game Dev'],
            ['Phaser', 'Game Dev'],
            ['Three.js', 'Game Dev'],
            ['WebGL', 'Game Dev'],
            ['Blender', 'Game Dev'],

            // Other
            ['Linux', 'OS/Infra'],
            ['Windows Server', 'OS/Infra'],
            ['macOS', 'OS/Infra'],
            ['Regex', 'Other'],
            ['WebAssembly (WASM)', 'Other'],
            ['PWA', 'Other'],
            ['SEO', 'Other'],
            ['Web Performance', 'Other'],
            ['Internationalization (i18n)', 'Other'],
            ['Technical Writing', 'Other'],
            ['Open Source', 'Other'],
            ['Low-Code/No-Code', 'Other'],
            ['RPA', 'Other'],
            ['Power BI', 'Other'],
            ['Tableau', 'Other'],
            ['Excel/VBA', 'Other'],
            ['SAP', 'Other'],
            ['Salesforce', 'Other'],
            ['ServiceNow', 'Other'],
            ['TOTVS', 'Other'],
        ];

        $rows = [];
        foreach ($skills as [$name, $category]) {
            $rows[] = [
                'name' => $name,
                'category' => $category,
                'aliases' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('skills')->upsert($chunk, ['name'], ['category', 'updated_at']);
        }
    }
}
